# Generated by Django 2.2.3 on 2019-07-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='file',
        ),
    ]
