# Generated by Django 2.2.1 on 2019-07-23 18:58

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190723_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media/images/'),
        ),
    ]
